### ISSUE TITLE
鼠标悬浮之后总是显示"data......"，有参数可以更改吗？

### ISSUE THREAD

**Issue by wikithink** [ChanningWong/REcharts3#2]
如题所述
比如饼图和环图，鼠标悬浮在某一部分时，悬浮显示的内容，第一行总是“data”，第二行才是真正的内容，请问可以在哪里更改吗？比如echarts.min.js?可以作为一个暂时的救急办法，谢谢！

**Comment by ChanningWong** [comment]
临时方案：
dat1 = aggregate(weight ~ feed, data = chickwts, mean)
p = pie(dat1, feed, weight, title = 'test')
p@option$series = lapply(p@option$series, function(x){
  x$name = '你的系列名称'
  x
})
p
